from layer import DerestLayer
from convolutional import DerestConvolutionalLayer
from fully_connected import DerestFullyConnectedLayer
from inception import DerestInceptionLayer
from dropout import DerestDropoutLayer
from norm import DerestNormLayer
from pool import DerestPoolLayer
from relu import DerestReluLayer
from softmax import DerestSoftmaxLayer
